// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuickBooksDemo.DAL.Context;

#nullable disable

namespace QuickBooksDemo.DAL.Migrations
{
    [DbContext(typeof(QuickBooksDemoContext))]
    partial class QuickBooksDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuickBooksDemo.Models.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuickBooksId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuickBooksSyncDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = "cust_001",
                            Address = "123 Main St, Springfield",
                            CustomerType = "Residential",
                            Email = "john@email.com",
                            Name = "John Smith",
                            Notes = "Prefers morning appointments",
                            Phone = "555-0100"
                        },
                        new
                        {
                            Id = "cust_002",
                            Address = "456 Industrial Blvd, Springfield",
                            CustomerType = "Commercial",
                            Email = "facilities@acme.com",
                            Name = "Acme Manufacturing",
                            Notes = "Requires safety check-in at front desk",
                            Phone = "555-0200"
                        });
                });

            modelBuilder.Entity("QuickBooksDemo.Models.Entities.Job", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal?>("ActualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssignedTechnicianId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuotedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTechnicianId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = "CCE_0001",
                            CreatedDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "cust_001",
                            Description = "Install EV charger in garage",
                            JobType = "Installation",
                            QuotedAmount = 1200.00m,
                            Status = "Quote"
                        },
                        new
                        {
                            Id = "CCE_0002",
                            AssignedTechnicianId = "tech_002",
                            CreatedDate = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "cust_002",
                            Description = "Emergency - partial power outage in building",
                            JobType = "ServiceCall",
                            QuotedAmount = 500.00m,
                            ScheduledDate = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = "CCE_0003",
                            ActualAmount = 275.00m,
                            AssignedTechnicianId = "tech_001",
                            CompletedDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "cust_001",
                            Description = "Replace faulty outlets in kitchen",
                            JobType = "Repair",
                            QuotedAmount = 250.00m,
                            ScheduledDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("QuickBooksDemo.Models.Entities.LineItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LaborHours")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaterialCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("LineItems");

                    b.HasData(
                        new
                        {
                            Id = "item_001",
                            Description = "Level 2 EV Charger",
                            JobId = "CCE_0001",
                            LaborCost = 400.00m,
                            LaborHours = 4,
                            MaterialCost = 600.00m
                        },
                        new
                        {
                            Id = "item_002",
                            Description = "Electrical panel upgrade",
                            JobId = "CCE_0001",
                            LaborCost = 200.00m,
                            LaborHours = 2,
                            MaterialCost = 150.00m
                        },
                        new
                        {
                            Id = "item_003",
                            Description = "Diagnose and repair circuit",
                            JobId = "CCE_0002",
                            LaborCost = 300.00m,
                            LaborHours = 3,
                            MaterialCost = 100.00m
                        },
                        new
                        {
                            Id = "item_004",
                            Description = "Replace 4 GFCI outlets",
                            JobId = "CCE_0003",
                            LaborCost = 195.00m,
                            LaborHours = 2,
                            MaterialCost = 80.00m
                        });
                });

            modelBuilder.Entity("QuickBooksDemo.Models.Entities.Technician", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            Id = "tech_001",
                            Active = true,
                            Email = "mike@electricco.com",
                            Name = "Mike Johnson",
                            Phone = "555-0301",
                            Specialties = "[\"residential\",\"service_calls\"]"
                        },
                        new
                        {
                            Id = "tech_002",
                            Active = true,
                            Email = "sarah@electricco.com",
                            Name = "Sarah Chen",
                            Phone = "555-0302",
                            Specialties = "[\"commercial\",\"high_voltage\",\"installation\"]"
                        });
                });

            modelBuilder.Entity("QuickBooksDemo.Models.Entities.Job", b =>
                {
                    b.HasOne("QuickBooksDemo.Models.Entities.Technician", "AssignedTechnician")
                        .WithMany("Jobs")
                        .HasForeignKey("AssignedTechnicianId");

                    b.HasOne("QuickBooksDemo.Models.Entities.Customer", "Customer")
                        .WithMany("Jobs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTechnician");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("QuickBooksDemo.Models.Entities.LineItem", b =>
                {
                    b.HasOne("QuickBooksDemo.Models.Entities.Job", "Job")
                        .WithMany("LineItems")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("QuickBooksDemo.Models.Entities.Customer", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("QuickBooksDemo.Models.Entities.Job", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("QuickBooksDemo.Models.Entities.Technician", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
